on:
  push:
    #branches: master
    #paths:
    #  - tests/testthat/out

name: windows-tests

jobs:
  tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: Rscript {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Edit config
        run: |
          git log -n 1 --pretty=format:"git config user.name '%an'; git config user.email '%ae'" | sh
        shell: bash

      - name: List config
        run: |
          git config -l
        shell: pwsh

      - name: List env var
        run: |
          env | sort
        shell: bash

      - name: Deploy package
        run: |
          git add tests/testthat/out-native
          git commit -m "Add Windows test results" || echo "No changes to commit"
          git push origin
        shell: pwsh
