on:
  push:
    #branches: master
    #paths:
    #  - tests/testthat/out

name: windows-tests

jobs:
  tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: Rscript {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Edit config
        run: |
          git log -n 1 --pretty=format:"git config user.name '%an'; git config user.email '%ae'" | sh
        shell: bash

      - name: Deploy package
        run: |
          git add tests/testthat/out-native
          if [[ $(git status --porcelain tests/testthat/out-native) == "" ]]
          then
            echo "No changes to commit"
          else
            git push origin
          fi
        shell: bash
